### ISSUE TITLE
Strange error causing port to close on raspberry pi (raspbian)

### ISSUE THREAD

**Issue by exxtremestuffs** [smithy212000/PortMiner#22]
So I got everything configured and set up just fine (the server.jar runs perfectly on its own), but every time I open portminer it gives a weird java error about "xterm" and shuts down.
`java.io.IOException: Cannot run program "xterm" (in directory "/home/pi/PortMiner"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:591)
	at com.lnicf.PortMiner.PortMiner.main(PortMiner.java:236)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 3 more
[23:27:16][INFO] Closing port 25565
`
I tried reinstalling and stuff, but am I supposed to have "xterm" in there or what because I'm really confused.

**Comment by soshimee** [comment]
install xterm.
