### ISSUE TITLE
Non-windows operating system support

### ISSUE THREAD

**Issue by soshimee** [smithy212000/PortMiner#31]
```
Exception while creating or running process.
java.io.IOException: Cannot run program "cmd": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:589)
	at java.base/java.lang.Runtime.exec(Runtime.java:448)
	at com.lnicf.PortMiner.PortMiner.main(PortMiner.java:211)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 4 more
```

**Comment by smithy212000** [comment]
What operating system

**Comment by soshimee** [comment]
I only have access to MacOS and Ubuntu Linux
